KPIAdmin/Models/ApplicationSecurity.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

KPIAdmin/Controllers/ApplicationSecuritiesController.cs
using System;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using System.Net.Http.Headers;
using Newtonsoft.Json;
using System.Threading.Tasks;
using System.Net;
using PagedList;
using PagedList.Mvc;
using System.IO;
using System.IO.Compression;
using System.Web.Security;
using KPIAdmin.Models;
using System.Data.Entity;

namespace KPIAdmin.Controllers
{
    public class ApplicationSecuritiesController : KPIController
    {
        private KPI_SecurityEntities_AppSecurity db = new KPI_SecurityEntities_AppSecurity();
        private KPI_SecurityEntities_Level dblevels = new KPI_SecurityEntities_Level();
        private KPI_SecurityEntities dbapps = new KPI_SecurityEntities();
        private KPI_SecurityEntities_User dbuser = new KPI_SecurityEntities_User();

        // GET: ApplicationSecurities
        public ActionResult AppSecurity()
        {
         
            var applications = new SelectList(dbapps.Applications.OrderBy(s => s.APName).Select(c => c.APName).ToList());
            ViewBag.Applications = applications;

            var users = new SelectList(dbuser.DirectoryUser_Load(0, null).Select(i => new { Text=i.KYDescription, Value=i.KYID }),"Value","Text");
            ViewBag.Users = users;

            IEnumerable<vwApplicationSecurity> AppSec = db.vwApplicationSecurities.AsQueryable().ToList();

            int numreq = AppSec.Count();

            int pageSize = 25;
            int pageNumber = 1;
            decimal mypgct = numreq / Convert.ToDecimal(pageSize);
            int mypagecount = Convert.ToInt32(Math.Ceiling(mypgct));
            ViewBag.mypagecount = mypagecount;

            var list = new List<SelectListItem>();

            for (int i = 1; i <= mypagecount; i++)
                list.Add(new SelectListItem { Text = i.ToString(), Value = i.ToString() });

            ViewBag.list = list;
            ViewBag.pagenum = pageNumber.ToString();



            return View(AppSec.OrderBy(s => s.APName).ThenBy(s => s.AUFullName).ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        public ActionResult AppSecurity([Bind(Include = "SEAPID,SEAUID,SELevel,SEAdmin,SEFlag1,SEDefault,SESecurityCode,SEUserName,SEDateAdd,SEDateChange,SEDateDelete")] vwApplicationSecurity applicationSecurity, string myaction, string referrer, Guid? SEAPID, Guid? SEAUID, string Applications, string Users, string currentFilter, string CurrentFilterU,string whichpage, string whichpagenum, string MyPagedList)
        {
            if (myaction == "Details")
            {
                if (SEAPID == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                vwApplicationSecurity app = db.vwApplicationSecurities.Find(SEAPID,SEAUID);
                if (app == null)
                {
                    return HttpNotFound();
                }
                return View(app);
            }
            else if (myaction == "Edit")
            {
                if (referrer == "Edit")
                {
                    try
                    {
                        if (ModelState.IsValid)
                        {
                            
                            applicationSecurity.SEDateChange = DateTime.Now;
                            db.Entry(applicationSecurity).State = EntityState.Modified;
                            db.SaveChanges();
                        }
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = ex.Message;

                    }
                    applicationSecurity.levelitems = dblevels.ApplicationLevels.Where(s => s.LVAPID == SEAPID).OrderBy(c => c.LVLevel).Select(c => new SelectListItem { Value = c.LVLevel.ToString(), Text = c.LVDescription.ToString() }).ToList();
                    return View(applicationSecurity);
                }
                else
                {
                    ModelState.Clear();
                    if (SEAPID == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    vwApplicationSecurity app = db.vwApplicationSecurities.Find(SEAPID,SEAUID);
                    if (app == null)
                    {
                        return HttpNotFound();
                    }
                    //app.levelitems = dblevels.ApplicationLevels.Where(s => s.LVAPID.Equals(SEAPID)).Select(c => new SelectListItem { Value = c.LVLevel.ToString(), Text = c.LVLevel.ToString() }).ToList();
                    app.levelitems = dblevels.ApplicationLevels.Where(s => s.LVAPID == SEAPID).OrderBy(c=> c.LVLevel).Select(c => new SelectListItem { Value = c.LVLevel.ToString(), Text = c.LVDescription.ToString() }).ToList();

                    return View(app);
                }

            }
            else if (SEAPID == null)
            {

                if (String.IsNullOrEmpty(Applications))
                {
                    Applications = currentFilter;
                }
                if (String.IsNullOrEmpty(Users))
                {
                    Users = CurrentFilterU;
                }

                ViewBag.CurrentFilter = Applications;
                ViewBag.CurrentFilterU = Users;

                var applications = new SelectList(dbapps.Applications.OrderBy(s => s.APName).Select(c => c.APName).ToList());
                ViewBag.Applications = applications;

                var users = new SelectList(dbuser.DirectoryUser_Load(0, null).Select(i => new { Text = i.KYDescription, Value = i.KYID }), "Value", "Text");
                ViewBag.Users = users;

                IEnumerable<vwApplicationSecurity> AppSec = db.vwApplicationSecurities.OrderBy(s => s.APName).ThenBy(s => s.AUFullName).AsQueryable().ToList();

                if (!String.IsNullOrEmpty(Applications))
                {
                   AppSec= AppSec.Where(s => s.APName.Equals(Applications));
                }
                if (!String.IsNullOrEmpty(Users))
                {
                    AppSec = AppSec.Where(s => s.SEAUID.Equals(new Guid(Users)));
                }

                int numreq = AppSec.Count();

                int pageSize = 25;
                int pageNumber = 1;
                decimal mypgct = numreq / Convert.ToDecimal(pageSize);
                int mypagecount = Convert.ToInt32(Math.Ceiling(mypgct));
                ViewBag.mypagecount = mypagecount;
                if (MyPagedList != "" && MyPagedList != null)
                {
                    pageNumber = Convert.ToInt32(MyPagedList);
                }
                else if (whichpagenum != "" && whichpagenum != null)
                {
                    pageNumber = Convert.ToInt32(whichpagenum);
                }
                if (pageNumber > mypagecount)
                {
                    pageNumber = 1;
                }
                switch (whichpage)
                {
                    case "Next":
                        pageNumber++;
                        break;
                    case "Last":
                        pageNumber = mypagecount;
                        break;
                    case "Previous":
                        pageNumber--;
                        break;
                    case "First":
                        pageNumber = 1;
                        break;
                }

                var list = new List<SelectListItem>();

                for (int i = 1; i <= mypagecount; i++)
                    list.Add(new SelectListItem { Text = i.ToString(), Value = i.ToString() });

                ViewBag.list = list;
                ViewBag.pagenum = pageNumber.ToString();

                return View(AppSec.ToPagedList(pageNumber, pageSize));


            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }






        // GET: ApplicationSecurities/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            vwApplicationSecurity applicationSecurity = db.vwApplicationSecurities.Find(id);
            if (applicationSecurity == null)
            {
                return HttpNotFound();
            }
            return View(applicationSecurity);
        }

        // GET: ApplicationSecurities/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ApplicationSecurities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SEAPID,SEAUID,SELevel,SEAdmin,SEFlag1,SEDefault,SESecurityCode,SEUserName,SEDateAdd,SEDateChange,SEDateDelete")] vwApplicationSecurity applicationSecurity)
        {
            if (ModelState.IsValid)
            {
                applicationSecurity.SEAPID = Guid.NewGuid();
                db.vwApplicationSecurities.Add(applicationSecurity);
                db.SaveChanges();
                
            }

            return View(applicationSecurity);
        }

        // GET: ApplicationSecurities/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            vwApplicationSecurity applicationSecurity = db.vwApplicationSecurities.Find(id);
            if (applicationSecurity == null)
            {
                return HttpNotFound();
            }

KPIAdmin/Views/ApplicationSecurities/AppSecurity.cshtml
@Html.Partial("HeaderView")

<div class="masterDivDetail" style="">

    @if (ViewBag.Error == null)
    {
        if ((Request.Params["myaction"] == null) || (Request.Params["myaction"] == "Default"))
        {

            @Html.Partial("ApplicationSecurity")

        }
        else if (Request.Params["myaction"] == "CreateSecurity")
        {

            @Html.Partial("CreateSecurity")

        }
        else if (Request.Params["myaction"] == "Details")
        {

            @Html.Partial("Details")

        }
        else if (Request.Params["myaction"] == "Edit" && Request.Params["referrer"] == "Edit")
        {

            @Html.Partial("Details")

        }
        else if (Request.Params["myaction"] == "Edit")
        {

            @Html.Partial("Edit")

        }

    }
    else
    {

        @Html.Partial("NoAccess")

    }

</div>

KPIAdmin/Views/ApplicationSecurities/ApplicationSecurity.cshtml
@model PagedList.IPagedList<KPIAdmin.Models.vwApplicationSecurity>
@using PagedList.Mvc;


<script type="text/javascript">
    $(document).ready(function () {

        $(function () {
            $('#Applications').change(function () {
                $('#obformfilter').submit();

            });
        });

        $(function () {
            $('#Users').change(function () {
                $('#obformfilter').submit();

            });
        });

        $('.joblink').click(function () {

            $(this).parents('form:first').submit();

        });

        $('#createlink').click(function () {
            $('#createform').submit();
        });

        $('#MyPagedList').change(function () {
            var pageName = $('#MyPagedList').find(":selected").text();
            $('#whichpagenum').val(pageName);
            $('#obformfilter').submit();
        });


            $('#pagelinkFirst').click(function () {
                $('#whichpage').val("First");
                document.forms[0].submit();
            });
            $('#pagelinkNext').click(function () {
                $('#whichpage').val("Next");
                $('#whichpagenum').val(@ViewBag.pagenum);
                document.forms[0].submit();
            });
            $('#pagelinkLast').click(function () {
                $('#whichpage').val("Last");
                document.forms[0].submit();
            });
            $('#pagelinkPrevious').click(function () {
                $('#whichpage').val("Previous");
                $('#whichpagenum').val(@ViewBag.pagenum);
                document.forms[0].submit();
            });

    });
</script>


@{
    MvcForm form;
    if (Request.QueryString["AppID"] != null)
    {
        form = Html.BeginForm("AppSecurity", "ApplicationSecurities", new { AppID = Request.QueryString["AppID"].ToString() }, FormMethod.Post, new { name = "obformfilter", id = "obformfilter" });
    }
    else
    {
        form = Html.BeginForm("AppSecurity", "ApplicationSecurities", FormMethod.Post, new { name = "obformfilter", id = "obformfilter" });
    }
    using (form)
    {
        @Html.AntiForgeryToken()
        <div style="width:100%;text-align:center;margin-bottom:0px;background-color:#f1f1f1;display:block;float:left;clear:both;">
            <div style="margin:0 auto;margin-left:auto;margin-right:auto;border:0px solid blue;width:auto;padding-bottom:5px;">
                <div style="margin-left:4px;margin-right:4px;display:inline-block;white-space: nowrap;">
                    <div class="searchdiv" style="">Application:</div>
                    <div class="searchdiv"> @Html.DropDownList("Applications", "* ALL")</div>
                </div>
                <div style="margin-left:4px;margin-right:4px;display:inline-block;white-space: nowrap;"><div class="searchdiv" style="">User: </div><div class="searchdiv">@Html.DropDownList("Users", "* ALL") </div></div>
                <input type="hidden" id="sortOrder" name="sortOrder" value="@ViewBag.CurrentSort" />
                <input type="hidden" id="whichpagenum" name="whichpagenum" value="" />
                <input type="hidden" id="whichpage" name="whichpage" value="" />
                <input type="hidden" name="myaction" value="Default" />



            </div>
        </div>
    }
}





<p>

    @{
        using (@Html.BeginForm("AppSecurity", "ApplicationSecurities", FormMethod.Post, new { name = "createform", id = "createform" }))
        {
            @Html.AntiForgeryToken()
            <input name="myaction" type="hidden" value="CreateApp" />
            <a class="headersubmit" id="createlink">Create New</a>
        }
    }

</p>



<table class="table">
    <tr>
        <th>
            Application
        </th>
        <th>
            User
        </th>
        <th>
            SE Level
        </th>
        <th>
            SE Admin
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @{
                    MvcForm form2;

                    if (Request.QueryString["AppID"] != null)
                    {
                        form2 = Html.BeginForm("AppSecurity", "ApplicationSecurities", new { AppID = Request.QueryString["AppID"].ToString() }, FormMethod.Post, new { id = "detailform" + @item.SEAPID + @item.SEAUID, name = "detailform" + @item.SEAPID + @item.SEAUID });
                    }
                    else
                    {
                        form2 = Html.BeginForm("AppSecurity", "ApplicationSecurities", FormMethod.Post, new { id = "detailform" + @item.SEAPID + @item.SEAUID, name = "detailform" + @item.SEAPID });
                    }

                    using (form2)
                    {
                        @Html.AntiForgeryToken()
                        <input type="hidden" name="SEAPID" value="@item.SEAPID" />
                        <input type="hidden" name="SEAUID" value="@item.SEAUID" />
                        <input type="hidden" name="myaction" value="Details" />
                        <a class="joblink" id="link-@item.SEAPID">  @Html.DisplayFor(modelItem => item.APName)</a>
                    }
                }


            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AUFullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LVDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SEAdmin)
            </td>
        </tr>
    }

</table>
<br />
@if (Convert.ToInt32(ViewBag.mypagecount) > 1)
{


    <div class="pagerfooter">


        @if (Convert.ToInt32(ViewBag.pagenum) != 1)
        {


            <a class="headersubmit pagerlink" id="pagelinkFirst">&lt;&lt;First</a>

            <a class="headersubmit pagerlink" id="pagelinkPrevious">&lt;Prev</a>
        }


        @Html.DropDownList("MyPagedList", new SelectList(ViewBag.list, "Text", "Value", ViewBag.pagenum.ToString()), new { sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, currentFilterU = ViewBag.CurrentFilterU })

        of @Model.PageCount


        @if (Convert.ToInt32(ViewBag.pagenum) < @Model.PageCount)
        {
            <a class="headersubmit pagerlink" id="pagelinkNext">Next&gt;</a>

            <a class="headersubmit pagerlink" id="pagelinkLast">Last&gt;&gt;</a>
        }

    </div>
}

KPIAdmin/Views/ApplicationSecurities/CreateSecurity.cshtml
@model KPIAdmin.Models.vwApplicationSecurity

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>ApplicationSecurity</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.SELevel, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SELevel, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SELevel, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.SEAdmin, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.SEAdmin)
                        @Html.ValidationMessageFor(model => model.SEAdmin, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.SEFlag1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.SEFlag1)
                        @Html.ValidationMessageFor(model => model.SEFlag1, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.SEDefault, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.SEDefault)
                        @Html.ValidationMessageFor(model => model.SEDefault, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.SESecurityCode, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SESecurityCode, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SESecurityCode, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.SEUserName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SEUserName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SEUserName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.SEDateAdd, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SEDateAdd, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SEDateAdd, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.SEDateChange, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SEDateChange, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SEDateChange, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.SEDateDelete, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SEDateDelete, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SEDateDelete, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

KPIAdmin/Views/ApplicationSecurities/Delete.cshtml
@model KPIAdmin.Models.vwApplicationSecurity

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>ApplicationSecurity</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.SELevel)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.SELevel)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.SEAdmin)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.SEAdmin)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.SEFlag1)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.SEFlag1)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.SEDefault)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.SEDefault)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.SESecurityCode)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.SESecurityCode)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.SEUserName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.SEUserName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.SEDateAdd)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.SEDateAdd)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.SEDateChange)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.SEDateChange)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.SEDateDelete)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.SEDateDelete)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

KPIAdmin/Views/ApplicationSecurities/Details.cshtml
@model KPIAdmin.Models.vwApplicationSecurity


<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.APName)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.APName)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.AUFullName)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.AUFullName)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.SELevel)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.LVDescription)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.SEAdmin)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.SEAdmin)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.SEFlag1)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.SEFlag1)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.SEDefault)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.SEDefault)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.SESecurityCode)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.SESecurityCode)
    </dd>


    <dt>
        @Html.DisplayNameFor(model => model.SEDateAdd)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.SEDateAdd)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.SEDateChange)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.SEDateChange)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.SEDateDelete)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.SEDateDelete)
    </dd>

</dl>
<div>

    @{

        MvcForm form2;

        if (Request.QueryString["AppID"] != null)
        {
            form2 = Html.BeginForm("Apps", "ApplicationSecurities", new { AppID = Request.QueryString["AppID"].ToString() }, FormMethod.Post, new { id = "detailform", name = "editform" });
        }
        else
        {
            form2 = Html.BeginForm("Apps", "ApplicationSecurities", FormMethod.Post, new { id = "detailform", name = "detailform" });
        }

        using (form2)
        {
            @Html.AntiForgeryToken()
            <input type="hidden" name="SEAPID" value="@Model.SEAPID" />
            <input type="hidden" name="SEAUID" value="@Model.SEAUID" />
            <input type="hidden" name="myaction" value="Edit" />
            <input type="submit" value="Edit" />
        }

    }

</div>